version: '3.8'
services:
  web:
    container_name: lazyweb-web
    build: .
    ports:
      - "9005:80"
    depends_on:
      - db
  db:
    container_name: lazyweb-db
    image: mysql:5.6
    restart: always
    volumes:
      - ./backup:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: snf1AvQ74DtF1PJp
      MYSQL_DATABASE: user
      MYSQL_USER: user
      MYSQL_PASSWORD: snf1AvQ74DtF1PJp
