version: '2'
services:
 apache:
   build: .
   ports:
    - "9000:80"
   volumes:
    - ./httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    - ./httpd-default.conf:/usr/local/apache2/conf/extra/httpd-default.conf:ro
 tomcat:
   image: vulhub/tomcat:8.5.19
